### ISSUE TITLE
500 error on teams route path for unauthenticated users

### ISSUE THREAD

**Issue by gathuku** [excid3/railshackathon.com#1]
When you click on team link(https://railshackathon.com/teams) when not authenticated an internal server error occurs

How to reproduce 

- Log out if already logged in 
- Click on `login` btn to navigate to login page 
- Click on `teams` link on navbar

**Comment by gathuku** [comment]
Looking at it :)

**Comment by excid3** [comment]
Looks like we just need a `user_signed_in?` here 👍 

https://github.com/excid3/railshackathon.com/blob/master/app/views/teams/index.html.erb#L4

**Comment by gathuku** [comment]
Thought of null safe `current_user&.team` but that even better.

**Comment by gathuku** [comment]
> Looks like we just need a `user_signed_in?` here 👍
> 
> https://github.com/excid3/railshackathon.com/blob/master/app/views/teams/index.html.erb#L4

I think wrapping the whole div with `user_signed_in?` is a good idea because the `create team` link need to be authenticated?
