### ISSUE TITLE
Validation missing for full name and email 

### ISSUE THREAD

**Issue by maniSHarma7575** [excid3/railshackathon.com#3]
**Present Behaviour**

on the account settings page

1. User is able to enter blank full name.
2. User can change his email without any email verification.
3. Also the 'Change your gravity' button is redirected to [https://en.gravatar.com/](https://en.gravatar.com/). Instead of opening a file-manager pop-up to select and update Gravatar.

<img width="1440" alt="Screenshot 2022-09-03 at 12 48 56 PM" src="https://user-images.githubusercontent.com/39980734/188260504-335fed2c-e0af-4fcf-b4cb-e5519230a314.png">
<img width="1440" alt="Screenshot 2022-09-03 at 12 49 14 PM" src="https://user-images.githubusercontent.com/39980734/188260510-a4f610ba-d7e7-4eee-90c5-5c67d7ffdd48.png">

**Excepted Behaviour**

1. Full name of the user should be mandatory.
2. Verification should be done if the user changes his email. Because in future if we need to launch some important emails from the platform then this user may lose track.
3. Change Gravitational behavior should be the same as in all other www.

**Comment by maniSHarma7575** [comment]
@excid3 Can I take this?

**Comment by excid3** [comment]
Just send me a PR 👍

**Comment by maniSHarma7575** [comment]
@excid3 Thanks!
PR: #4

**Comment by excid3** [comment]
Closed by #4
