### ISSUE TITLE
Set current year for newly created resources

### ISSUE THREAD

**Issue by cjilbert504** [excid3/railshackathon.com#38]
Now that we are planning to have a year column to distinguish teams and entries we need to also set the year for newly created teams and entries to the current year in which they are being created.

I think we can probably just set this attribute in an `after_initialize` callback much like we are by setting the `github_url` for entries already and set the attribute value to the result of calling `Time.current.year`

**Comment by excid3** [comment]
You can use the Attributes API:

```ruby
class User < ApplicationRecord
  attribute :year, default: 2023
end
```

**Comment by cjilbert504** [comment]
Ah good call! I never remember about that one
